### ISSUE TITLE
Missing concept of IN_PRODUCTION, only have not DEBUG

### ISSUE THREAD

**Issue by walkerh** [CenterForOpenScience/scrapi#142]
Currently, scrapi/settings/local.py (when copied from scrapi/settings/local-dist.py) has no flag for designating the concept of being "in production". This forces code that needs to make this distinction to use the expression:

    from scrapi.settings import local
    in_production = not local.DEBUG

This approach is flawed:

1. The current version of scrapi/settings/local-dist.py has `DEBUG = False`, so most running development instances would consider themselves to be truly "in production".
2. During later stages of integration testing, it may be perfectly reasonable to have both DEBUG and IN_PRODUCTION set to False.

## Motivating example

Some code specifically for supporting developer environments and training should be turned off in production. In particular, `scrapi/harvesters/fakejsonharvester.py` should not generate documents in production, but it should generate documents in new development environments.

**Comment by fabianvf** [comment]
We have moved checks that would require the check of "IN_PRODUCTION" to the testing suite. Thank you for the suggestion!
