### ISSUE TITLE
Add documentation for cleaning database at http://localhost:9200/share_v2/_harvestername

### ISSUE THREAD

**Issue by mehanig** [CenterForOpenScience/scrapi#151]
smthn like <code>url -XDELETE 'localhost:9200/share_v2/stepic' </code>

**Comment by fabianvf** [comment]
Good idea, might even be better to provide a task that can clear out all storage providers. Will look into this.

**Comment by kms6bn** [comment]
I added a description of how to do this to the documentation here: 
https://osf.io/wur56/wiki/Running%20the%20Harvesters/
(see the bottom of the page)
