### ISSUE TITLE
New harvester - Lake Winnipeg Basin Information Network

### ISSUE THREAD

**Issue by erinspace** [CenterForOpenScience/scrapi#261]
http://130.179.67.140/

**Comment by jeffreyliu3230** [comment]
Just sent a pull request.

**Comment by erinspace** [comment]
#284 is the PR for reference when it gets merged!

**Comment by fabianvf** [comment]
If you are submitting a pull request that closes an issue, you can reference that issue in the pull request (with ```closes #260```) and it will do this:
closes #260 

Then when the pull request is merged the issue will automatically be closed.

**Comment by jeffreyliu3230** [comment]
Good to know! Thanks!

**Comment by kms6bn** [comment]
@erinspace This also looks like it is closed
