### ISSUE TITLE
Cyberleninka not harvesting new records

### ISSUE THREAD

**Issue by erinspace** [CenterForOpenScience/scrapi#307]
Cyberleninka on staging hasn't gotten any new documents since its initial run on July 7 
https://staging.osf.io/share/?q=*&optional=source%3Acyberleninka&sort=Date#

The resumption tokens are all the exact same, and might rely on cookies of some sort, or something in the header, that isn't working with our periodic harvesting.

We should look into this, and figure out why new results aren't being added.

**Comment by fabianvf** [comment]
For now, cyberleninka has been disabled

**Comment by kms6bn** [comment]
@erinspace it looks like Cyberleninka is working for now, can you close this issue?

Thank you!!

**Comment by erinspace** [comment]
@kms6bn good call! Yes indeed.
