### ISSUE TITLE
"Avian community structure and incidence of human West Nile infection" shows up multiple times

### ISSUE THREAD

**Issue by fabianvf** [CenterForOpenScience/scrapi#330]

**Comment by amandafrench** [comment]
Ooh, maybe you've detected some plagiarism. ;) Or it's just a popular topic.

**Comment by fabianvf** [comment]
No, comes up about six times from datacite. 

https://osf.io/share/?q=Avian+community+structure+and+incidence+of+human+West+Nile+infection&sort=Relevance

**Comment by fabianvf** [comment]
Actually, looked into it more, and it looks like it's multiple datasets with different IDs, but stemming from the same project. Closing this for now, as it isn't really a bug. Will leave a note in the dataone harvester to look into this though. I think we experienced something similar with dryad.
